Implementing '--pbeq' CLI option in bin/pdb_charmm_energy.

diff --git a/bin/pdb_charmm_energy b/bin/pdb_charmm_energy
--- a/bin/pdb_charmm_energy
+++ b/bin/pdb_charmm_energy
@@ -1,8 +1,38 @@
 #!/bin/bash
 
-INPUT_PDB=$1
-INPUT_RTF=$2 # topology
-INPUT_PRM=$3 # parameters
+INPUT_PDB=
+INPUT_RTF= # topology
+INPUT_PRM= # parameters
+
+PBEQ=
+
+while [ $# -gt 0 ]
+do
+    case $1 in
+        -t|--topology|--topo|--top)
+            INPUT_RTF="$2"
+            shift
+            ;;
+        -p|--parameters|--param|--par|--prm)
+            INPUT_PRM="$2"
+            shift
+            ;;
+        --pbeq)
+            PBEQ=1
+            ;;
+        -*) echo "`basename $0`: unknown option $1" >&2 ; exit 1 ;;
+        *)
+            test -z "$INPUT_PDB" && INPUT_PDB=$1
+            ;;
+    esac
+    shift
+done
+
+if [ -z "$INPUT_PDB" -o -z "$INPUT_RTF" -o -z "$INPUT_PRM" ]
+then
+    echo "`basename $0`: either input PDB, or topology, or parameters are missing" >&2
+    exit 1
+fi
 
 RTF_BASE=$(basename $INPUT_RTF)
 PRM_BASE=$(basename $INPUT_PRM)
@@ -12,7 +42,7 @@ TMPDIR=$(mktemp --directory)
 cp $INPUT_RTF $INPUT_PRM $TMPDIR/
 sed 's/HIS/HSD/g' $INPUT_PDB > $TMPDIR/input.pdb
 
-cat > $TMPDIR/energy.inp <<END
+cat > $TMPDIR/energy.inp <<ENDSCRIPT
 !Taken from https://www.charmm.org/wiki//index.php/CHARMM:The_Basics
 !Read in RTF and Parameter files
 OPEN UNIT 1 CARD READ NAME $RTF_BASE
@@ -50,9 +80,19 @@ HBUILD SELEct HYDRogen END
 PRINt COOR SELEct .NOT. INITialized END
  
 ENERgy
+ENDSCRIPT
 
-STOP
+if [ -n "$PBEQ" ]
+then
+
+cat >> $TMPDIR/energy.inp <<ENDSCRIPT
+PBEQ
+   SOLVE epsw 80 epsp 2 ncel 200 dcel 2 maxi 1000 select all end
 END
+ENDSCRIPT
+fi
+
+echo STOP >> $TMPDIR/energy.inp
 
 (
     cd $TMPDIR
